Updated player.cpp, player.h, enemy.h, ghost.cpp, entity.h
Entity.h now has the Directions enum for its children classes, and player.h + player.cpp are fully functioning without any errors.
enemy.h & ghost.cpp seems to have an undefined reference to a missing vtable, so currently looking through the possible causes.