Updated spell.h
This fixes the undefined references to vtable spell. 
However, there's still an undefined reference to Spell::Update(int, level) that still needs to be resolved in crystalcave.cpp line 83.